### ISSUE TITLE
Error when using current Ensembl Version

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/sageseqr#8]
This is an error with `biomaRt` but the workflow can pass the correct variable to `useMart` if the most recent ENSEMBL version is to be used.
```
Note: requested host was redirected from
sep2019.archive.ensembl.org to https://www.ensembl.org:80/biomart/martservice
This often occurs when connecting to the archive URL for the current Ensembl release
You can check the current version number using listEnsemblArchives()
```

**Comment by jgockley62** [comment]
I've been getting time-out errors with the sep2019 version. Not sure what the issue is but I think its on BioMarts end. I've switched to using jul2019 and that works fine for a temporary fix.

**Comment by kelshmo** [comment]
This is a `biomaRt` thing.
